apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: infrastructure
spec:
  encryptedData:
    token: AgBXMS/DgsU6stmZu5Xib64PzMnFYoXSQJiXwcWrwliSv9aNWYsSLuhml32fX4FnObBfSxVsf4D4sy7XzWcDj2aChQ4Y+xXWXc7QUVgoXSBCYicvzphfEFkuElRxW+FN/vMSxfIOpFWTL2DO4fACTTEXW4jdjZ8CaNoooBrwz3yrZtyUmf+yTAjSptjiYt4S3YRvvZA3KbyzvZ7Ly3aS/5u4j9ZdYfIky2pIpAQ5/86Ruq73K1mury8u1kezA6yynGUgI5KREUdjzq61zh3pE6hNuLoyeGow0+0IQATytKujgDe94gtMErw/TqMDLLjt4rkhvbKZRZe/W63YAUFfask2UvkEY55qGOrMb4MFrJ9ciB9J8p3cu0ci7l7b/Y5ELaGIu6RI+D8tAuW7ufxUbjdn+UMh80fgFe42IQVthpZeDUDV/wDVQoxyAveItQZ2KtMOntwmvwW43MLpOt+FsWgblVRKIiS5lXNI4SanPWanWnnUmgnaYxWyRZeD6BpBX8k1So9zW3FgJRxrWoTYN5rZ+BXzvWLIrHP4sYiE8OG0SEbMXJNk8Xf2EU8ftJEh2y2KnOh4Rv9gvUM5bPk/F0xcS+ijj3Y6HWChDSQV6ayyT5YebM7vOdIqMHw2BFUydAH/FL84ydVlE7BBxViNeWoBCRFMUfri8nEvQFASnDlkQz3cywh6Jtqnu4ltSEzZZIB2meaEkp/3wkWX8obIwDQnYzI00IFK8p5rVjgQg4BeHnt+24wkiL9s9FDb3a6F2uYKeeZDVkoJbzwIfE2kxncbRUiX9wraxPSwUH3B87Gog6vBS57pgazgEMm0QiSvlYFh2sBWjoisUHzQFyNl5klFaqsxXPg9inlrxqmKt0Z3dCdFC+lq42VkwmzvGuQieshboDJnQGNZ5L4p9XKPAcB6ReVmybH27LrkwaYn4G6K15Fc2+Ev43hh
  template:
    metadata:
      name: cloudflared-token
      namespace: infrastructure
