apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBBL7/lX5BUdpJtDMOZodSCO3UmkZlxcIwPyDEUXFoHKMeRxmHzVNFObHYe8/mV5v5Th+9pxMSulgeb7ca2QCGNdS/fQHPEg7GpfIxwiEdB9LSWrOkjgvoiaNu4D87tGP1giVOeCGn8DqjNsbC3rrjx4JaWvC6UB4xy4cij5RvLXNasR0PFNgonrfEIFFMX5mfnGkeyPX0ZeCAu3NCmjiDQLeBdwtnkU0JOeHtZqOGDVrXtyfQaV4ykiYgs9f+iTRarHb1emxioLMn10vkhs0Dl34t3A2CO8D1fnCLjU2zktpz3mUv5cwtHzrb5OuFwDE54NaB8OzZnRK9NWGdq5DhbniUIj9EiGUqV9vugKWdwcXfbLZDzYjkHnO+YJHV93b8eeZxChBJOBbK7HYd5h4A5yKYn3XKbrHP2cZ73tcJww9FJBTaws+bkuCKHjIoQiM3US4Ki5CoK92MBJRmXCr2JlataqurRawracJBzHDUQLorPjKH35HXQtoHiWQ+tKD2EyNgGI8WYnM+Wb9CrZVozlNIy+IZpbatOFhdRukA7lhpIG0RWIdotS0qaSml+TLmsxvhqvHBhv6N1cH38RG6OX6YAlc1rDS6JRuEU0dfI3Sit3lJBAhghJw7uc4z02M5qD654nNFlcurGsXtt3Tb9fAmgORE6qTKddLcknTZz8UXDo/Afs1cmSoyzEc6x+xRyxyPj9+TMb2klRCqXS7+Cu6HzaHk4HOHzUZ22RAiweA1C/mX/klRa54Dh/QFTu633ccpJWw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
